# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-08-09 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
