# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-08-31 14:25
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='agents'),
        ),
        migrations.AddField(
            model_name='shop',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='agents'),
        ),
    ]
