# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-09-02 14:06
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_auto_20210831_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='navs'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='shops'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='subcategories'),
        ),
    ]
