# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-09-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_auto_20210902_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pick',
            field=models.BooleanField(default=False),
        ),
    ]
