# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-18 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190217_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayadvert',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 10, 23, 25, 140000, tzinfo=utc)),
        ),
    ]
