# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-08-09 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210808_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayadvert',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 6, 59, 26, 839000, tzinfo=utc)),
        ),
    ]
