# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-08-09 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210809_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayadvert',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 14, 32, 8, 606000, tzinfo=utc)),
        ),
    ]
