# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-08-22 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210811_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayadvert',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 18, 3, 39, 812000, tzinfo=utc)),
        ),
    ]
