# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-08-31 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210822_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayadvert',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 14, 25, 13, 688000, tzinfo=utc)),
        ),
    ]
