# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-09-16 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210902_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayadvert',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 8, 44, 15, 460000, tzinfo=utc)),
        ),
    ]
