# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-11-12 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210916_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayadvert',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 9, 26, 51, 408000, tzinfo=utc)),
        ),
    ]
